export type SectionType =
  | 'getting-started'
  | 'suggested-structure'
  | 'folder-overview'
  | 'config'
  | 'new-project'
  | 'component'
  | 'type'
  | 'inject'
  | 'slice'
  | 'page'
  | 'api'
  | 'crud'
